### ISSUE TITLE
When using `keepImport`, ES2015 imports are changed into require() calls

### ISSUE THREAD

**Issue by adambrenecki** [michalkvasnicak/babel-plugin-css-modules-transform#78] opened 2018-02-13 04:12 UTC
Hi! 

First, thanks for making/working on this plugin, it's super useful!

If I have something like the following in `Navigation.js`:

```
import css from "./Navigation.css"
```

The output ends up looking like this:

```
require("./Navigation.css");

var css = {
  "navigation": "Navigation__navigation___pwCdF",
  "navItem": "Navigation__navItem___5NFIM",
  "dropdown": "Navigation__dropdown___32xYA",
  "nav-item": "Navigation__nav-item___2Xzpo"
};
```

IMO the first line should be `import "./Navigation.css"`, to match the import style used in the original file.

I've configured Babel to not transform imports, and all of my other imports remain in ES2015 import format, so it seems most likely to me that it's this plugin that's doing it I think?

**Comment by michalkvasnicak** [comment] 2018-02-13 07:31
Hello,

yes it is caused by this plugin because it doesn't have anything to do with `modules` settings in `babel-preset-env` or similar.

But I think that in case of css files it does not matter if it is an import or a require call. Does it cause some problems in your project?

**Comment by adambrenecki** [comment] 2018-02-20 23:39
None for me personally, because currently all the downstream projects for the library I'm building use Webpack, which supports `require()` calls natively.

But as I understand it Rollup doesn't, so I _think_ this would cause problems if this output was then used with Rollup which was configured with a CSS plugin but not also a `require()` plugin? I'm not sure how common that case is though.

**Comment by michalkvasnicak** [comment] 2018-03-01 13:26
I don't know, unless there is a real issue in this matter there is nothing to solve :) but I think that if rollup will be configured to resolve `require` calls, everything will be okay.

**Comment by michalkvasnicak** [comment] 2018-03-01 13:26
Closing for now as this not really issue if you are users are using webpack.

**Closed by michalkvasnicak** 2018-03-01 13:26 UTC
