### ISSUE TITLE
processCss file path

### ISSUE THREAD

**Issue by olegakbarov** [michalkvasnicak/babel-plugin-css-modules-transform#13] opened 2016-06-01 12:31 UTC
Thanks for cool project! 

Though config seems straightforward i keep getting same output:

```
/Users/oleg/code/extreme/node_modules/babel-core/lib/transformation/file/index.js:591
      throw err;
      ^

Error: /Users/oleg/code/extreme/src/server-entry.js: Module '/Users/oleg/code/extreme/src/utils/runtimeStyles.js' does not exist or is not a function.
    at /Users/oleg/code/extreme/node_modules/babel-plugin-css-modules-transform/build/index.js:116:35
    at Array.forEach (native)
    at PluginPass.Program (/Users/oleg/code/extreme/node_modules/babel-plugin-css-modules-transform/build/index.js:77:32)
    at newFn (/Users/oleg/code/extreme/node_modules/babel-traverse/lib/visitors.js:310:19)
    at NodePath._call (/Users/oleg/code/extreme/node_modules/babel-traverse/lib/path/context.js:78:18)
    at NodePath.call (/Users/oleg/code/extreme/node_modules/babel-traverse/lib/path/context.js:49:17)
    at NodePath.visit (/Users/oleg/code/extreme/node_modules/babel-traverse/lib/path/context.js:108:12)
    at TraversalContext.visitQueue (/Users/oleg/code/extreme/node_modules/babel-traverse/lib/context.js:174:16)
    at TraversalContext.visitSingle (/Users/oleg/code/extreme/node_modules/babel-traverse/lib/context.js:124:19)
    at TraversalContext.visit (/Users/oleg/code/extreme/node_modules/babel-traverse/lib/context.js:219:19)

```
I swear to god i have the this file in proper directory with this content:

````
module.exports = function runtimeStyles(data, filename) {
  console.log(data, filename);
};
```

Babel config follows:

```
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": [
    ["css-modules-transform", {
      "processCss": "./src/utils/runtimeStyles.js"
    }],
    ["module-alias", [
      { "src": "./src/containers", "expose": "containers" },
      { "src": "./src/components", "expose": "components" },
      { "src": "./src/components/layouts", "expose": "layouts" },
      { "src": "./src/actions", "expose": "actions" },
      { "src": "./src/constants", "expose": "utils" },
      { "src": "./src/utils", "expose": "utils" }
    ]]
  ]
}
```

Any ideas what might cause this behaviour?

**Comment by michalkvasnicak** [comment] 2016-06-01 16:07
Hello, this is weird. I've tried to reproduce this but without luck. What version of `babel-plugin-css-modules-transform` are you using?

Have you tried to run it without `module-alias` plugin? Maybe it is the cause of problem.

**Comment by olegakbarov** [comment] 2016-06-01 18:23
Yes, that do helped!  Thank you! Should have try it by myself though. 😓

**Comment by olegakbarov** [comment] 2016-06-01 18:32
Damn it. I forgot, that i monkey-patched the module before dispatching home from work. It doesn't work.

**Comment by michalkvasnicak** [comment] 2016-06-01 18:38
Can you try to create clean project just with your `src/utils/runtimeStyles.js` and `css-modules` plugin? Something is causing that your file is not loaded or function is not exported. There is a test case for this so I really don't think there is a bug.

**Comment by jacobwalton** [comment] 2016-06-08 10:50
I'm having a similar issue with `preprocessCSS` using v0.1.1 and following babel config:
```
"babel": {
    "presets": ["es2015", "react"],
    "plugins": [
      "transform-class-properties",
      "transform-decorators-legacy",
      "transform-object-rest-spread",
      ["css-modules-transform", {
          "preprocessCss": "./processScss.js",
          "extensions": [".scss"]
      }]
    ]
  }
```

**Comment by olegakbarov** [comment] 2016-06-08 11:04
I ended up using vanilla require hook. So idk, probably we can close it...

**Comment by michalkvasnicak** [comment] 2016-06-08 11:11
I'll take a look on weekend. This is really weird. 

@jacobwalton is your error same as mentioned above? Can you attach stack trace please?

**Comment by jacobwalton** [comment] 2016-06-08 11:30
Yes, very similar error:
```
/Users/jwalton/Sites/which/reviews-and-advice/front-end/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/index.js:614
      throw err;
      ^

Error: /Users/jwalton/Sites/which/reviews-and-advice/front-end/withDom.js: Module '/Users/jwalton/Sites/which/reviews-and-advice/front-end/processScss.js' does not exist or is not a function.
    at /Users/jwalton/Sites/which/reviews-and-advice/front-end/node_modules/babel-plugin-css-modules-transform/build/index.js:116:35
    at Array.forEach (native)
    at PluginPass.Program (/Users/jwalton/Sites/which/reviews-and-advice/front-end/node_modules/babel-plugin-css-modules-transform/build/index.js:77:32)
    at newFn (/Users/jwalton/Sites/which/reviews-and-advice/front-end/node_modules/babel-traverse/lib/visitors.js:310:19)
    at NodePath._call (/Users/jwalton/Sites/which/reviews-and-advice/front-end/node_modules/babel-traverse/lib/path/context.js:78:18)
    at NodePath.call (/Users/jwalton/Sites/which/reviews-and-advice/front-end/n
```
Contents of processScss.js:
```
var sass = require('node-sass');

module.exports = function processScss(data) {
  return sass.renderSync({
    data: data
  }).css.toString('utf8');
};
```

**Comment by jacobwalton** [comment] 2016-06-08 11:35
Thanks for the library btw, and thanks for looking into the issue. 👍

**Comment by jrajav** [comment] 2016-06-16 22:58
Getting exactly the same error with

```

**Comment by jrajav** [comment] 2016-06-16 22:58
Getting exactly the same error with

```
[
          "css-modules-transform",
          {
            "preprocessCss": "./postcssparser.js",
            "extensions": [".css"]
          }
        ]```

and

```var postcss = require('postcss')
var parser = require('sugarss')

module.exports = function postcssparser(data, filename) {
  return postcss().process(
    data,
    {
      parser: parser
    }
  ).css
}```

**Comment by michalkvasnicak** [comment] 2016-06-17 07:35
Hello, I am sorry, really occupied these days. I'll take a look as soon as possible.

**Comment by michalkvasnicak** [comment] 2016-06-17 10:27
I tried to reproduce this problem so I made a minimal project in branch `require-error-case` but I am unable to reproduce this. Could you try this branch please? 

Run `npm install` inside `error_case` directory and then `npm run test`.

**Comment by mac-r** [comment] 2016-06-19 15:44
Fantastic lib, but same issue...

**Comment by mac-r** [comment] 2016-06-19 16:49
@michalkvasnicak i did what u asked to reproduce the error in your branch.

`Run npm install inside error_case directory and then npm run test`
gives this:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'test' ]
2 info using npm@2.15.5
3 info using node@v5.6.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info pretest application-name@0.0.1
6 info test application-name@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info application-name@0.0.1 Failed to exec test script
9 verbose stack Error: application-name@0.0.1 test: `babel src`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:100:13)
9 verbose stack     at EventEmitter.emit (events.js:185:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:100:13)
9 verbose stack     at ChildProcess.emit (events.js:185:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid application-name@0.0.1
11 verbose cwd babel-plugin-css-modules-transform/error_case
12 error Darwin 14.5.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
14 error node v5.6.0
15 error npm  v2.15.5
16 error code ELIFECYCLE
17 error application-name@0.0.1 test: `babel src`
17 error Exit status 1
18 error Failed at the application-name@0.0.1 test script 'babel src'.
18 error This is most likely a problem with the application-name package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     babel src
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs application-name
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls application-name
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by michalkvasnicak** [comment] 2016-06-19 16:55
@mac-r it is weird. I am getting output:

```

> application-name@0.0.1 test /Users/Michal/Work/babel-plugin-css-modules-transform/error_case
> babel src

test
const styles = {};
module.exports = function processCss() {
    console.log('test');
};
```

**Comment by michalkvasnicak** [comment] 2016-06-19 16:57
@mac-r Can you try to upgrade npm to latest version and then redo whole process from start?

**Comment by mac-r** [comment] 2016-06-19 17:14
@michalkvasnicak what's your node version? it's same with `5.6.0`. Tried `6.2.2` too, but there are other issues not related with this specific lib (ppl say that many modules are not yet compatible with it).

**Comment by michalkvasnicak** [comment] 2016-06-19 17:37
I have npm `3.9.3` and node `6.2.1`. It's weird because I can't reproduce this problem that you all have. Could you create a minimal failing project and upload it to gist or something? Then I'll have better chances to resolve this issue.

Could you try to run `node_modules/.bin/babel` in `error_case` directory? It should do the same thing as `npm run test`.

**Comment by mac-r** [comment] 2016-06-19 17:53
my current hack is just replacing classes in `renderToString` results (with those which are in `css-modules.json`). your lib still helps a lot! we definitely need to make it better together. I'll try creating a docker container during the week, so we could be sure about having identical env. ;)

**Comment by michalkvasnicak** [comment] 2016-06-19 18:22
Thank you very much. I'm glad that this lib helps. :) Docker container is good idea. I'll try it too if I find some free time.

**Comment by michalkvasnicak** [comment] 2016-06-21 09:47
@mac-r I created `Dockerfile` in `error_case` directory along with README how to test it. Output on my machine for `docker run error_case` is:

```
npm info it worked if it ends with ok
npm info using npm@3.9.5
npm info using node@v6.2.2
npm info lifecycle application-name@0.0.1~pretest: application-name@0.0.1
npm info lifecycle application-name@0.0.1~test: application-name@0.0.1

> application-name@0.0.1 test /var/www/html
> babel src

test
const styles = {};
module.exports = function processCss() {
    console.log('test');
};

npm info lifecycle application-name@0.0.1~posttest: application-name@0.0.1
npm info ok 
```

**Comment by michalkvasnicak** [comment] 2016-06-21 09:50
@mac-r maybe it has something to do with `npm < 3.0`. But feel free to update test case to match more realistic use case so we can be sure. Maybe a part from your project with libraries you are using?

**Comment by michalkvasnicak** [comment] 2016-06-21 09:51
@olegakbarov @jacobwalton @jrajav what versions of node and npm do you have guys?

**Comment by olegakbarov** [comment] 2016-06-21 10:42
```
$ node -v
v5.10.1

$ npm -v
3.8.6
```

**Comment by jacobwalton** [comment] 2016-06-21 10:57
Node v5.8.0
NPM v3.7.3

**Comment by jrajav** [comment] 2016-06-21 17:25
Node v6.2.1
NPM v3.9.6

Sorry I haven't been able to contribute more information or reproductions -- we haven't had time to investigate this issue more and are just not using 'composes' anymore, for the time being.

**Comment by mac-r** [comment] 2016-06-22 04:44
my npm version is `3.6.0`

**Comment by michalkvasnicak** [comment] 2016-06-22 07:21
@olegakbarov @mac-r @jrajav @jacobwalton Guys are you using this plugin as part of babel build process `$ babel src` or as `babel-register` module in server entry point file?

**Comment by olegakbarov** [comment] 2016-06-22 08:39
As i mentioned, i've transitioned to vanilla hooks, but at the moment of stumbling upon the bug i've used `babel-registry`

**Comment by michalkvasnicak** [comment] 2016-06-22 09:08
Ok thank you, I think there is a problem when this plugin is used as part of `babel-register` I will look at it later today.

**Comment by jacobwalton** [comment] 2016-06-22 09:49
I'm using it with `babel-register` via mocha compilers, e.g. 
```
mocha --require spec/support/test-setup.js --compilers js:babel-core/register,jsx:babel-core/register --recursive spec
```

**Comment by jrajav** [comment] 2016-06-22 20:44
@michalkvasnicak Indeed we are, yes.

**Comment by TylorShin** [comment] 2016-06-26 07:12
Also having same problem with 'babel-register'.

btw, I really want to say thanks to your library.

**Comment by michalkvasnicak** [comment] 2016-06-26 19:18
Ok so I found a simple solution. You need to pass `ignore` option to `babel-register` hook, which ignores utility functions.

E.g.

```js
require('babel-register')({
    ignore: /processCss\.js$/
});
const styles = require('./style.css');
```

**Comment by michalkvasnicak** [comment] 2016-06-26 19:20
It has something to do with the way how `babel-register` modifies `require`. So by passing `ignore` option you are telling babel to require given processors using original `require` function without any transforms.

**Comment by TylorShin** [comment] 2016-06-27 01:36
@michalkvasnicak Thanks! I'll try your solution after work!

**Comment by michalkvasnicak** [comment] 2016-06-30 07:39
@olegakbarov @jacobwalton @mac-r @TylorShin Could you confirm if this workaround works?

**Comment by TylorShin** [comment] 2016-06-30 09:32
sorry I was too busy check solution. I'll check this at the weekend.

**Comment by jrajav** [comment] 2016-07-02 21:40
@michalkvasnicak It still doesn't work for me.

I removed ` --compilers js:babel-register` from my mocha command, so it is now just `BABEL_DISABLE_CACHE=1 NODE_ENV=test mocha \"src/**/*.spec.{js,jsx}\" -r mocha.setup.js`.

My mocha.setup.js:

```
require('babel-register')({
    ignore: /postcssparser\.js$/
})

const chai = require('chai')
const expect = chai.expect
const dirtyChai = require('dirty-chai')
const chaiEnzyme = require('chai-enzyme')
const jsdom = require('jsdom')

chai.use(dirtyChai)

chai.use(chaiEnzyme())

global.expect = expect

global.document = jsdom.jsdom()
global.window = document.defaultView
global.navigator = window.navigator
```

My postcssparser.js:

```
var postcss = require('postcss')
var parser = require('sugarss')

module.exports = function (data, filename) {
  return postcss().process(
    data,
    {
      parser: parser
    }
  ).css
}
```

.babelrc:

```
{
  "presets": [
    "es2015",
    "react"
  ],
  "plugins": [
    ["babel-root-slash-import", {
      "rootPathSuffix": "src"
    }]
  ],
  "env": {
    "test": {
      "plugins": [        
        [
          "css-modules-transform",
          {
            "preprocessCss": "./postcssparser.js"
          }
        ],
        "rewire"
      ]
    }
  }
}
```

And a sample test file:

```
import React from 'react'
import { shallow } from 'enzyme'

import Footer from '/app/Footer'

describe('<Footer />', () => {
  it('should render a div', () => {
    const wrapper = shallow(<Footer />)
    const feedback = wrapper.find('#feedback')

    expect(feedback).to.be.present()
  })
})
```

<Footer /> is using a css module with react-css-modules. With this setup, I get this error:

```
/Users/jrajav/dev/repo copy/node_modules/babel-core/lib/transformation/file/index.js:591
      throw err;
      ^

Error: /Users/jrajav/dev/repo copy/src/actions/detailsActions.spec.js: Module '/Users/jrajav/dev/repo copy/postcssparser.js' does not exist or is not a function.
    at /Users/jrajav/dev/repo copy/node_modules/babel-plugin-css-modules-transform/build/index.js:116:35
    at Array.forEach (native)
    at PluginPass.Program (/Users/jrajav/dev/repo copy/node_modules/babel-plugin-css-modules-transform/build/index.js:77:32)
    at newFn (/Users/jrajav/dev/repo copy/node_modules/babel-traverse/lib/visitors.js:301:19)
    at NodePath._call (/Users/jrajav/dev/repo copy/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/jrajav/dev/repo copy/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/jrajav/dev/repo copy/node_modules/babel-traverse/lib/path/context.js:106:12)
    at TraversalContext.visitQueue (/Users/jrajav/dev/repo copy/node_modules/babel-traverse/lib/context.js:167:16)
    at TraversalContext.visitSingle (/Users/jrajav/dev/repo copy/node_modules/babel-traverse/lib/context.js:118:19)
    at TraversalContext.visit (/Users/jrajav/dev/repo copy/node_modules/babel-traverse/lib/context.js:211:19)
    at Function.traverse.node (/Users/jrajav/dev/repo copy/node_modules/babel-traverse/lib/index.js:161:17)
    at traverse (/Users/jrajav/dev/repo copy/node_modules/babel-traverse/lib/index.js:83:12)
    at File.transform (/Users/jrajav/dev/repo copy/node_modules/babel-core/lib/transformation/file/index.js:548:35)
    at /Users/jrajav/dev/repo copy/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/Users/jrajav/dev/repo copy/node_modules/babel-core/lib/transformation/file/index.js:563:16)
    at Pipeline.transform (/Users/jrajav/dev/repo copy/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at Object.transformFileSync (/Users/jrajav/dev/repo copy/node_modules/babel-core/lib/api/node.js:144:10)
    at compile (/Users/jrajav/dev/repo copy/node_modules/babel-register/lib/node.js:129:20)
    at loader (/Users/jrajav/dev/repo copy/node_modules/babel-register/lib/node.js:158:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jrajav/dev/repo copy/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/jrajav/dev/repo copy/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/jrajav/dev/repo copy/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/jrajav/dev/repo copy/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/jrajav/dev/repo copy/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
```

**Comment by michalkvasnicak** [comment] 2016-07-03 16:53
@jrajav pls try to run your tests using `--compilers js:mocha.setup.js` if it does not work, create a new js file with content 

```js
require('babel-register')({
    ignore: /postcssparser\.js$/
})
```

and use it as compiler. In my minimal test case it works.

**Comment by michalkvasnicak** [comment] 2016-07-03 17:10
`README.md` is updated to reflect those requirements to run with `mocha` or `babel-register`.

**Comment by jrajav** [comment] 2016-07-03 21:42
Doesn't work for me with `--compilers`, either - same error. I'm actually trying it with `--compilers js:mocha.setup.js,jsx:mocha.setup.js` since the components themselves are jsx, though - is it possible that is requiring babel-register twice?

**Comment by michalkvasnicak** [comment] 2016-07-04 05:33
I think it is possible. Try to require only compiler for js and pass `extensions` config to babel-register.

```js
require('babel-register')({
    ignore: /postcssparser\.js$/,
    extensions: ['.js', '.jsx']
})
```

**Comment by michalkvasnicak** [comment] 2016-07-04 05:39
@jrajav try to run only one spec file. Maybe mocha is requiring compilers for every spec file?

**Comment by jrajav** [comment] 2016-07-04 15:08
I did try running it on a single spec file, yes. The babel-register extensions option also does not help.

**Comment by michalkvasnicak** [comment] 2016-07-04 15:13
@jrajav this is weird. I don't know why is `babel-register` resolving all those functions to an empty object. If there is a way to resolve this, it should work without any configuration.

**Comment by pioneer32** [comment] 2016-08-14 01:23
Faced the same issue. Adding "ignore": [ "tools/**/*.postcssparser.js" ] to .babelrc solved it.

**Comment by michalkvasnicak** [comment] 2016-08-14 08:05
@pioneer32 yes this is the same solution as in this [comment](https://github.com/michalkvasnicak/babel-plugin-css-modules-transform/issues/13#issuecomment-230163063)

**Comment by michalkvasnicak** [comment] 2016-09-02 11:38
Now it seems that you only need to specify your `processCss` require as ignored in `babel-register`. But be aware, if you set `ignore` option, you need to explicitly ignore `node_modules` too.

```js
require('babel-register')({
    ignore: /myProcessCss\.js|node_modules/
});
```

**Closed by michalkvasnicak** 2016-09-02 11:38 UTC

**Comment by michalkvasnicak** [comment] 2016-09-02 11:41
See test case in directory `error_case` of this branch https://github.com/michalkvasnicak/babel-plugin-css-modules-transform/tree/require-error-case

There is docker container so you can try it, just follow steps in `README.md`.
